[Randomizer]
; Weapons receive a random upgrade level from 0 to the previously used maximum
RandomizeWeaponUpgrade = True

; Weapons get a random infusion
RandomizeWeaponInfusion = True

; Enable randomization of shop weapons
ReinforceShopWeapons = False

; Randomization from only the top half of the possible options ([max/2; max])
EasyUpgrades = False


[AutoEquip]
; Auto-equipper main switch
AutoEquipToggle = True

; Here you can exclude some items from auto equipping
AutoEquipArmor = True;
AutoEquipRings = True;

; All staves, chimes, talismans, flames are left-handed
LeftHandedCatalysts = True

; Reduce stats requirements for items
; 0 = Disabled, no requirements reduction 
; 1 = Halved
; 2 = Zero requirements, you can use everything
LessWeaponRequirements = 0
